# Generated by Django 5.1.7 on 2025-04-02 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseInfoDetails',
            fields=[
                ('CaseInfoDetailsId', models.AutoField(primary_key=True, serialize=False)),
                ('stateId', models.IntegerField()),
                ('districtId', models.IntegerField()),
                ('unitId', models.IntegerField()),
                ('Office', models.TextField(max_length=255)),
                ('letterNo', models.CharField(max_length=100)),
                ('caseDate', models.DateTimeField()),
                ('caseType', models.CharField(max_length=100)),
                ('subject', models.TextField(max_length=1000)),
                ('caseNo', models.CharField(max_length=100)),
                ('firNo', models.CharField(max_length=255)),
                ('author', models.TextField(max_length=200)),
                ('toAddr', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=255)),
                ('filePath', models.TextField()),
                ('fileHash', models.CharField(max_length=64)),
                ('caseDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='caseInfoFiles.caseinfodetails')),
            ],
        ),
    ]
