# Generated by Django 5.1.7 on 2025-04-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0003_remove_caseinfodetails_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseinfodetails',
            options={'permissions': [('View_searchcaseFiles', 'can search the case and file details')]},
        ),
    ]
