# Generated by Django 5.1.7 on 2025-04-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0004_alter_caseinfodetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseinfodetails',
            options={'permissions': [('view_searchcaseFiles', 'can search the case and file details')]},
        ),
    ]
