# Generated by Django 5.1.7 on 2025-04-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0007_fileusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseinfodetails',
            options={'permissions': [('view_searchcaseFiles', 'can search the case and file details'), ('add_filepreviewapi', 'can preview a file')]},
        ),
    ]
