# Generated by Django 5.1.7 on 2025-04-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0009_filedetails_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
