# Generated by Django 5.1.7 on 2025-04-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0012_filedetails_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caseInfoFiles.filedetails'),
        ),
    ]
