# Generated by Django 5.1.7 on 2025-04-23 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0013_notification_file'),
        ('mdm', '0013_casestatus_rename_filetypes_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseinfodetails',
            name='caseStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.casestatus'),
        ),
        migrations.AddField(
            model_name='caseinfodetails',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
