# Generated by Django 5.1.7 on 2025-04-24 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0015_fileaccessrequest'),
        ('mdm', '0013_casestatus_rename_filetypes_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.fileclassification'),
        ),
    ]
