# Generated by Django 5.1.7 on 2025-04-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0018_fileaccessrequest_requested_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileAccessPermission',
        ),
    ]
