# Generated by Django 5.1.7 on 2025-04-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0019_delete_fileaccesspermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccessrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
