# Generated by Django 5.1.7 on 2025-04-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0021_caseinfodetails_division_favouritefiles_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='division',
        ),
    ]
