# Generated by Django 5.1.7 on 2025-04-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0022_remove_notification_division'),
        ('mdm', '0013_casestatus_rename_filetypes_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.divisionmaster'),
        ),
    ]
