# Generated by Django 5.1.7 on 2025-04-30 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0023_notification_division'),
        ('mdm', '0013_casestatus_rename_filetypes_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccessrequest',
            name='divsion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.divisionmaster'),
        ),
    ]
