# Generated by Django 5.1.7 on 2025-04-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0024_fileaccessrequest_divsion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileaccessrequest',
            old_name='divsion',
            new_name='division',
        ),
    ]
