# Generated by Django 5.1.7 on 2025-04-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0025_rename_divsion_fileaccessrequest_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccessrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revoked', 'Revoked'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
