# Generated by Django 5.1.7 on 2025-05-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0026_fileaccessrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetails',
            name='filestage',
            field=models.CharField(blank=True, choices=[('Enquiry', 'enquiry'), ('I/O', 'i/o'), ('Crime', 'crime')], max_length=20, null=True),
        ),
    ]
