# Generated by Django 5.1.7 on 2025-05-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0027_filedetails_filestage'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetails',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
