# Generated by Django 5.1.7 on 2025-05-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0028_filedetails_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinfodetails',
            name='caseDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
