# Generated by Django 5.1.7 on 2025-05-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0029_alter_caseinfodetails_casedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedetails',
            name='filestage',
        ),
        migrations.AddField(
            model_name='filedetails',
            name='documentType',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caseinfodetails',
            name='caseNo',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='caseinfodetails',
            name='caseStatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='classification',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='fileType',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
