# Generated by Django 5.1.7 on 2025-05-09 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0030_remove_filedetails_filestage_and_more'),
        ('mdm', '0015_generallookup_lookuporder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_classification', to='mdm.generallookup'),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='documentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_type', to='mdm.generallookup'),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='fileType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_type', to='mdm.generallookup'),
        ),
    ]
