# Generated by Django 5.1.7 on 2025-05-10 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0031_alter_filedetails_classification_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('mdm', '0015_generallookup_lookuporder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccessrequest',
            name='case_details_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caseInfoFiles.caseinfodetails'),
        ),
        migrations.AddField(
            model_name='fileaccessrequest',
            name='department',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='department',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='requestedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('UPLOAD_APPROVAL', 'Upload Approval'), ('ACCESS_REQUEST', 'Access Request'), ('GENERIC', 'Generic')], default='GENERIC', max_length=30),
        ),
        migrations.CreateModel(
            name='FileUploadApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('revoked', 'Revoked'), ('denied', 'Denied')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('case_details_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caseInfoFiles.caseinfodetails')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.divisionmaster')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caseInfoFiles.filedetails')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_approver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
