# Generated by Django 5.1.7 on 2025-05-10 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0032_fileaccessrequest_case_details_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='file',
        ),
    ]
