# Generated by Django 5.1.7 on 2025-05-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0033_remove_notification_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadapproval',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
