# Generated by Django 5.1.7 on 2025-05-11 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0034_fileuploadapproval_created_at'),
        ('mdm', '0022_designationhierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinfodetails',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.division'),
        ),
        migrations.AlterField(
            model_name='favouritefiles',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.division'),
        ),
        migrations.AlterField(
            model_name='fileaccessrequest',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.division'),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.division'),
        ),
        migrations.AlterField(
            model_name='fileuploadapproval',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.division'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.division'),
        ),
    ]
