# Generated by Django 5.1.7 on 2025-05-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0037_fileaccessrequest_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccessrequest',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileaccessrequest',
            name='revoke_enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileaccessrequest',
            name='revoke_startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
