# Generated by Django 5.1.7 on 2025-05-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('statusId', models.AutoField(primary_key=True, serialize=False)),
                ('statusName', models.CharField(max_length=100)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=150, unique=True)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignationMaster',
            fields=[
                ('designationId', models.AutoField(primary_key=True, serialize=False)),
                ('designationName', models.CharField(max_length=100)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileClassification',
            fields=[
                ('fileClassificationId', models.AutoField(primary_key=True, serialize=False)),
                ('fileClassificationName', models.CharField(max_length=100)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('fileTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('fileTypeName', models.CharField(max_length=100)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralLookUp',
            fields=[
                ('lookupId', models.AutoField(primary_key=True, serialize=False)),
                ('lookupName', models.CharField(max_length=100)),
                ('CategoryId', models.IntegerField()),
                ('lookupOrder', models.IntegerField(blank=True, null=True)),
                ('active', models.CharField(default='Y')),
                ('lastmodifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('stateId', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.CharField(max_length=100, unique=True)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('divisionId', models.AutoField(primary_key=True, serialize=False)),
                ('divisionName', models.CharField(max_length=250, unique=True)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.department')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designationId', models.AutoField(primary_key=True, serialize=False)),
                ('designationName', models.CharField(max_length=100)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('department', models.ManyToManyField(to='mdm.department')),
                ('division', models.ManyToManyField(to='mdm.division')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=50, unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictMaster',
            fields=[
                ('districtId', models.AutoField(primary_key=True, serialize=False)),
                ('districtName', models.CharField(max_length=100)),
                ('localName', models.CharField(max_length=200)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('stateId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.statemaster')),
            ],
        ),
        migrations.CreateModel(
            name='UnitMaster',
            fields=[
                ('unitId', models.AutoField(primary_key=True, serialize=False)),
                ('unitName', models.CharField(max_length=100)),
                ('typeId', models.IntegerField()),
                ('parentUnit', models.IntegerField()),
                ('actualStrength', models.IntegerField()),
                ('sanctionedStrength', models.IntegerField()),
                ('talukID', models.IntegerField()),
                ('address1', models.CharField(blank=True, max_length=250, null=True)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('districtId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.districtmaster')),
                ('stateId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.statemaster')),
            ],
        ),
        migrations.CreateModel(
            name='DesignationHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mdm.designation')),
                ('parent_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='mdm.designation')),
            ],
            options={
                'unique_together': {('parent_designation', 'child_designation')},
            },
        ),
    ]
