# Generated by Django 5.1.7 on 2025-03-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionMaster',
            fields=[
                ('divisionId', models.AutoField(primary_key=True, serialize=False)),
                ('divisionName', models.CharField(max_length=250, unique=True)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=50, unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('stateId', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.CharField(max_length=100, unique=True)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictMaster',
            fields=[
                ('districtId', models.AutoField(primary_key=True, serialize=False)),
                ('districtName', models.CharField(max_length=100, unique=True)),
                ('localName', models.CharField(max_length=200)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('stateId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.statemaster')),
            ],
        ),
    ]
