# Generated by Django 5.1.7 on 2025-05-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('smtpId', models.AutoField(primary_key=True, serialize=False)),
                ('smtpServerName', models.TextField()),
                ('portNo', models.IntegerField()),
                ('encryption', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_by', models.IntegerField(null=True)),
            ],
        ),
    ]
