# Generated by Django 5.1.7 on 2025-05-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0002_smtpsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpsettings',
            name='encryption',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='modified_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='smtpServerName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
