# Generated by Django 5.1.7 on 2025-03-20 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0002_alter_districtmaster_districtname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationMaster',
            fields=[
                ('districtId', models.AutoField(primary_key=True, serialize=False)),
                ('designationName', models.CharField(max_length=100)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitMaster',
            fields=[
                ('unitId', models.AutoField(primary_key=True, serialize=False)),
                ('unitName', models.CharField(max_length=100)),
                ('typeId', models.IntegerField()),
                ('parentUnit', models.IntegerField()),
                ('actualStrength', models.IntegerField()),
                ('sanctionedStrength', models.IntegerField()),
                ('talukID', models.IntegerField()),
                ('address1', models.CharField(max_length=250)),
                ('address2', models.CharField(max_length=250)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('districtId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.districtmaster')),
                ('stateId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.statemaster')),
            ],
        ),
    ]
