# Generated by Django 5.1.7 on 2025-03-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0003_designationmaster_unitmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmaster',
            name='address2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
