# Generated by Django 5.1.7 on 2025-05-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0003_alter_smtpsettings_encryption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='designationName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
