# Generated by Django 5.1.7 on 2025-05-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0004_alter_designation_designationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='mdm.department'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='division',
            field=models.ManyToManyField(blank=True, null=True, to='mdm.division'),
        ),
    ]
