# Generated by Django 5.1.7 on 2025-03-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0004_alter_unitmaster_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmaster',
            name='address1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
