# Generated by Django 5.1.7 on 2025-03-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0005_alter_unitmaster_address1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designationmaster',
            old_name='districtId',
            new_name='designationId',
        ),
    ]
