# Generated by Django 5.1.7 on 2025-06-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0005_alter_designation_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDomain',
            fields=[
                ('domainId', models.AutoField(primary_key=True, serialize=False)),
                ('domainName', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
