# Generated by Django 5.1.7 on 2025-07-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0006_emaildomain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DesignationMaster',
        ),
    ]
