# Generated by Django 5.1.7 on 2025-03-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0006_rename_districtid_designationmaster_designationid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permissionID', models.AutoField(primary_key=True, serialize=False)),
                ('permissionName', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
