# Generated by Django 5.1.7 on 2025-03-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0007_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
