# Generated by Django 5.1.7 on 2025-10-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0008_designationmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='lastmodifiedBy',
            field=models.IntegerField(default=1),
        ),
    ]
