# Generated by Django 5.1.7 on 2025-03-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0008_delete_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permissionID', models.AutoField(primary_key=True, serialize=False)),
                ('permissionName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', to='mdm.permission'),
        ),
    ]
