# Generated by Django 5.1.7 on 2025-03-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0009_permission_role_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
