# Generated by Django 5.1.7 on 2025-10-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0009_designation_lastmodifiedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='division',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='lastmodifiedBy',
        ),
    ]
