# Generated by Django 5.1.7 on 2025-10-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0010_remove_designation_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='mdm.department'),
        ),
        migrations.AddField(
            model_name='designation',
            name='division',
            field=models.ManyToManyField(blank=True, null=True, to='mdm.division'),
        ),
    ]
