# Generated by Django 5.1.7 on 2025-04-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0011_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileClassification',
            fields=[
                ('fileClassificationId', models.AutoField(primary_key=True, serialize=False)),
                ('fileClassificationName', models.CharField(max_length=100)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileTypes',
            fields=[
                ('fileTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('fileTypeName', models.CharField(max_length=100)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
