# Generated by Django 5.1.7 on 2025-04-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0012_fileclassification_filetypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('statusId', models.AutoField(primary_key=True, serialize=False)),
                ('statusName', models.CharField(max_length=100)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='FileTypes',
            new_name='FileType',
        ),
    ]
