# Generated by Django 5.1.7 on 2025-05-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0013_casestatus_rename_filetypes_filetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLookUp',
            fields=[
                ('lookupId', models.AutoField(primary_key=True, serialize=False)),
                ('lookupName', models.CharField(max_length=100)),
                ('CategoryId', models.IntegerField()),
                ('active', models.CharField(default='Y')),
                ('lastmodifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
