# Generated by Django 5.1.7 on 2025-05-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0014_generallookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='generallookup',
            name='lookupOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
