# Generated by Django 5.1.7 on 2025-05-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0015_generallookup_lookuporder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=150, unique=True)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
