# Generated by Django 5.1.7 on 2025-05-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0016_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionmaster',
            name='departmentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.department'),
        ),
    ]
