# Generated by Django 5.1.7 on 2025-05-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0017_divisionmaster_departmentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisionmaster',
            name='departmentId',
        ),
    ]
