# Generated by Django 5.1.7 on 2025-05-10 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0018_remove_divisionmaster_departmentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('divisionId', models.AutoField(primary_key=True, serialize=False)),
                ('divisionName', models.CharField(max_length=250, unique=True)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.department')),
            ],
        ),
    ]
