# Generated by Django 5.1.7 on 2025-05-10 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0019_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designationId', models.AutoField(primary_key=True, serialize=False)),
                ('designationName', models.CharField(max_length=100)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.department')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.division')),
            ],
        ),
    ]
