# Generated by Django 5.1.7 on 2025-05-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0020_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='division',
        ),
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ManyToManyField(to='mdm.department'),
        ),
        migrations.AddField(
            model_name='designation',
            name='division',
            field=models.ManyToManyField(to='mdm.division'),
        ),
    ]
