# Generated by Django 5.1.7 on 2025-05-11 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0021_remove_designation_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignationHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mdm.designation')),
                ('parent_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='mdm.designation')),
            ],
            options={
                'unique_together': {('parent_designation', 'child_designation')},
            },
        ),
    ]
