# Generated by Django 5.1.7 on 2025-05-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caseInfoFiles', '0035_alter_caseinfodetails_division_and_more'),
        ('mdm', '0022_designationhierarchy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DivisionMaster',
        ),
    ]
