# Generated by Django 5.1.7 on 2025-03-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kgid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobileno',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
