# Generated by Django 5.1.7 on 2025-04-27 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0013_casestatus_rename_filetypes_filetype'),
        ('users', '0002_activeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='designationmaster',
        ),
        migrations.RemoveField(
            model_name='user',
            name='divisionmaster',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.CreateModel(
            name='UserDivisionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.designationmaster')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.divisionmaster')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'division')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.ManyToManyField(through='users.UserDivisionRole', to='mdm.divisionmaster'),
        ),
    ]
