# Generated by Django 5.1.7 on 2025-05-11 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0022_designationhierarchy'),
        ('users', '0003_remove_user_designationmaster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='division',
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.designation'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.role'),
        ),
        migrations.DeleteModel(
            name='UserDivisionRole',
        ),
    ]
