# Generated by Django 5.1.7 on 2025-03-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_roles_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictMaster',
            fields=[
                ('districtId', models.AutoField(primary_key=True, serialize=False)),
                ('districtName', models.CharField(max_length=100, unique=True)),
                ('localName', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
