# Generated by Django 5.1.7 on 2025-05-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0023_delete_divisionmaster'),
        ('users', '0004_remove_user_division_user_designation_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='designation',
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.ManyToManyField(blank=True, related_name='designation', to='mdm.designation'),
        ),
    ]
