# Generated by Django 5.1.7 on 2025-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_districtmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtmaster',
            name='active',
            field=models.CharField(default='Y'),
        ),
    ]
