# Generated by Django 5.1.7 on 2025-05-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_designation_user_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='set_password',
            field=models.BooleanField(default=False),
        ),
    ]
