# Generated by Django 5.1.7 on 2025-03-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_districtmaster_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionMaster',
            fields=[
                ('divisionId', models.AutoField(primary_key=True, serialize=False)),
                ('divisionName', models.CharField(max_length=250, unique=True)),
                ('active', models.CharField(default='Y')),
                ('lastModifiedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
