# Generated by Django 5.1.7 on 2025-03-18 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_divisionmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='divisionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.divisionmaster'),
        ),
    ]
