# Generated by Django 5.1.7 on 2025-03-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_divisionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='divisionId',
            new_name='division',
        ),
    ]
