# Generated by Django 5.1.7 on 2025-03-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0001_initial'),
        ('users', '0011_alter_user_kgid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictMaster',
        ),
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.divisionmaster'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.role'),
        ),
        migrations.DeleteModel(
            name='DivisionMaster',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
