# Generated by Django 5.1.7 on 2025-03-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0002_alter_districtmaster_districtname'),
        ('users', '0012_delete_districtmaster_alter_user_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='division',
        ),
        migrations.AddField(
            model_name='user',
            name='divisionmaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.divisionmaster'),
        ),
    ]
