# Generated by Django 5.1.7 on 2025-03-20 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0006_rename_districtid_designationmaster_designationid'),
        ('users', '0013_remove_user_division_user_divisionmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designationmaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm.designationmaster'),
        ),
    ]
